{
     
  "Facebook_API_ID": "",
  "Facebook_API_SECRET": "",
  
  "URLSCAN_API_KEY":"",

  "SHODAN_API_KEY":"",  
  
  "BING_API_KEY": "",
  
  "VirusTotal_API_KEY": "",
  
  "BinaryEdge_API_KEY": ""
  
}
