{
     
  "FACEBOOK_API_ID": "",
  "FACEBOOK_API_SECRET": "",
  
  "CENSYS_API_KEY":"",
  "CENSYS_SECRET":"",
  
  "URLSCAN_API_KEY":"",

  "SHODAN_API_KEY":"",  
  
  "BING_API_KEY": "",
  
  "VIRUSTOTAL_API_KEY": "",
  
  "BINARYEDGE_API_KEY": ""
  
}
